name: 🧰 Devenv

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main]

jobs:
  test:
    name: 🧪 Devenv Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ❄️ Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Set up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv

      - name: 🔧 Install devenv
        run: nix profile install nixpkgs#devenv

      - name: ✅ Run Formatting checks
        run: devenv shell "just format"
